
use super::trivia_nodes::Trivia;

#[derive(Clone)]
pub enum Token {

    /* Reserved keywords as of Python 3.13 */
    FalseToken(u32, u32, Vec<Box<Trivia>>),
    TrueToken(u32, u32, Vec<Box<Trivia>>),
    NoneToken(u32, u32, Vec<Box<Trivia>>),
    AndToken(u32, u32, Vec<Box<Trivia>>),
    AsToken(u32, u32, Vec<Box<Trivia>>),
    AssertToken(u32, u32, Vec<Box<Trivia>>),
    AsyncToken(u32, u32, Vec<Box<Trivia>>),
    AwaitToken(u32, u32, Vec<Box<Trivia>>),
    BreakToken(u32, u32, Vec<Box<Trivia>>),
    ClassToken(u32, u32, Vec<Box<Trivia>>),
    ContinueToken(u32, u32, Vec<Box<Trivia>>),
    DefToken(u32, u32, Vec<Box<Trivia>>),
    DelToken(u32, u32, Vec<Box<Trivia>>),
    ElifToken(u32, u32, Vec<Box<Trivia>>),
    ElseToken(u32, u32, Vec<Box<Trivia>>),
    ExceptToken(u32, u32, Vec<Box<Trivia>>),
    FinallyToken(u32, u32, Vec<Box<Trivia>>),
    ForToken(u32, u32, Vec<Box<Trivia>>),
    FromToken(u32, u32, Vec<Box<Trivia>>),
    GlobalToken(u32, u32, Vec<Box<Trivia>>),
    IfToken(u32, u32, Vec<Box<Trivia>>),
    ImportToken(u32, u32, Vec<Box<Trivia>>),
    InToken(u32, u32, Vec<Box<Trivia>>),
    IsToken(u32, u32, Vec<Box<Trivia>>),
    LambdaToken(u32, u32, Vec<Box<Trivia>>),
    NonlocalToken(u32, u32, Vec<Box<Trivia>>),
    NotToken(u32, u32, Vec<Box<Trivia>>),
    OrToken(u32, u32, Vec<Box<Trivia>>),
    PassToken(u32, u32, Vec<Box<Trivia>>),
    RaiseToken(u32, u32, Vec<Box<Trivia>>),
    ReturnToken(u32, u32, Vec<Box<Trivia>>),
    TryToken(u32, u32, Vec<Box<Trivia>>),
    WhileToken(u32, u32, Vec<Box<Trivia>>),
    WithToken(u32, u32, Vec<Box<Trivia>>),
    YieldToken(u32, u32, Vec<Box<Trivia>>),

    /* Operator or delimiters */
    PlusToken(u32, u32, Vec<Box<Trivia>>),
    MinusToken(u32, u32, Vec<Box<Trivia>>),
    MultiplyToken(u32, u32, Vec<Box<Trivia>>),
    DivideToken(u32, u32, Vec<Box<Trivia>>),
    ModuloToken(u32, u32, Vec<Box<Trivia>>),
    FloorDivideToken(u32, u32, Vec<Box<Trivia>>),
    MatricesToken(u32, u32, Vec<Box<Trivia>>),
    ShiftLeftToken(u32, u32, Vec<Box<Trivia>>),
    ShiftRightToken(u32, u32, Vec<Box<Trivia>>),
    BitAndToken(u32, u32, Vec<Box<Trivia>>),
    BitOrToken(u32, u32, Vec<Box<Trivia>>),
    BitXorToken(u32, u32, Vec<Box<Trivia>>),
    BitInvertToken(u32, u32, Vec<Box<Trivia>>),
    ColonAssignToken(u32, u32, Vec<Box<Trivia>>),
    LessThanToken(u32, u32, Vec<Box<Trivia>>),
    GreaterThanToken(u32, u32, Vec<Box<Trivia>>),
    LessOrEqualToken(u32, u32, Vec<Box<Trivia>>),
    GreaterOrEqualToken(u32, u32, Vec<Box<Trivia>>),
    EqualToken(u32, u32, Vec<Box<Trivia>>),
    NotEqualToken(u32, u32, Vec<Box<Trivia>>),
    PowerToken(u32, u32, Vec<Box<Trivia>>),
    LeftParenToken(u32, u32, Vec<Box<Trivia>>),
    RightParenToken(u32, u32, Vec<Box<Trivia>>),
    LeftSquareBracketToken(u32, u32, Vec<Box<Trivia>>),
    RightSquareBracketToken(u32, u32, Vec<Box<Trivia>>),
    LeftCurlyBracketToken(u32, u32, Vec<Box<Trivia>>),
    RightCurlyBracketToken(u32, u32, Vec<Box<Trivia>>),
    SemicolonToken(u32, u32, Vec<Box<Trivia>>),
    CommaToken(u32, u32, Vec<Box<Trivia>>),
    PeriodToken(u32, u32, Vec<Box<Trivia>>),
    ColonToken(u32, u32, Vec<Box<Trivia>>),
    AssignToken(u32, u32, Vec<Box<Trivia>>),
    ArrowToken(u32, u32, Vec<Box<Trivia>>),
    PlusAssignToken(u32, u32, Vec<Box<Trivia>>),
    MinusAssignToken(u32, u32, Vec<Box<Trivia>>),
    MultiplyAssignToken(u32, u32, Vec<Box<Trivia>>),
    DivideAssignToken(u32, u32, Vec<Box<Trivia>>),
    ModuloAssignToken(u32, u32, Vec<Box<Trivia>>),
    AndAssignToken(u32, u32, Vec<Box<Trivia>>),
    XorAssignToken(u32, u32, Vec<Box<Trivia>>),
    OrAssignToken(u32, u32, Vec<Box<Trivia>>),
    FloorDivideAssignToken(u32, u32, Vec<Box<Trivia>>),
    MatricesAssignToken(u32, u32, Vec<Box<Trivia>>),
    ShiftLeftAssignToken(u32, u32, Vec<Box<Trivia>>),
    ShiftRightAssignToken(u32, u32, Vec<Box<Trivia>>),
    PowerAssignToken(u32, u32, Vec<Box<Trivia>>),
    EllipsisToken(u32, u32, Vec<Box<Trivia>>),

    /* Literal */
    NameToken(u32, u32, Box<String>, Vec<Box<Trivia>>),
    NumberToken(u32, u32, Box<String>, Vec<Box<Trivia>>),
    StringToken(u32, u32, Vec<Box<String>>, Vec<Box<Trivia>>),

    /* Special */
    NewlineToken(u32, u32, char, char, Vec<Box<Trivia>>),
    IndentToken(u32, u32, Vec<Box<Trivia>>),
    DedentToken(u32, u32, Vec<Box<Trivia>>),
    TypeCommentToken(u32, u32, Box<str>, Vec<Box<Trivia>>),
    EofToken(u32, u32, Vec<Box<Trivia>>),

    Invalid
}